### ISSUE TITLE
"Unable to locate credentials" error in build stage

### ISSUE THREAD

**Issue by hakanutku** [mariamrf/py-lambda-action#9]
I was testing this action in my deployment process. In 'Deploy code to Lambda' stage, after installing my dependencies, I got the following error: 
```
Unable to locate credentials. You can configure credentials by running "aws configure".
Using the layer in the function...
Unable to locate credentials. You can configure credentials by running "aws configure".
Done.
```
And the action completed without giving errors. But lambda function and layer was not deployed correctly. I set up AWS credentials in Github secrets too. Do you know how can I fix it?

**Comment by mariamrf** [comment]
Could you please share how this was resolved in case someone else bumps into the same issue?

**Comment by hakanutku** [comment]
Feeling really stupid now, but it was a typo issue...
